"""Initial migration.

Revision ID: 14554f865197
Revises: 
Create Date: 2025-03-27 21:00:03.642233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14554f865197'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=150), nullable=False, server_default='default.png'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
